language: php
php:
  - '7.1'

services:
  - mysql
  - postgresql
  
before_script:
  - sudo apt-get -y install snmpd
  - sudo apt-get -y install snmp
  - sudo apt-get -y install snmp-mibs-downloader
  - sudo apt-get -y install snmptrapd
  - ./tests/install_dep.sh

env:
  - DB=mysql DBVER=1
  - DB=pgsql DBVER=1
  
script:
  - ./tests/launch_test.sh
